[package]
name = "cfg_attrs"
version = "1.0.0"
authors = ["Antikyth"]
description = "An alternative to #[cfg_attr(...)] that is easier to use with doc comments."
license = "MPL-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = "2.0.39"
